spring.application.name=PennyWise
spring.datasource.url=jdbc:postgresql://localhost:5432/money_tracker
spring.datasource.username=postgres
spring.datasource.password=aman123
jwt.secret=MyVeryStrongPennyWiseSecretKeyForJWTAuthentication2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
